import Vue from 'vue'

import { Button,Form,FormItem,Input,Container,Header,Aside,Main,Menu,Submenu,MenuItemGroup,MenuItem,Descriptions,DescriptionsItem,Tag,Breadcrumb,BreadcrumbItem,Upload,Table,TableColumn,InfiniteScroll,Option,Select,Card,Pagination,Scrollbar} from 'element-ui'

Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Container)
Vue.use(Main)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(Descriptions)
Vue.use(DescriptionsItem)
Vue.use(Tag)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Upload)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(InfiniteScroll)
Vue.use(Option)
Vue.use(Select)
Vue.use(Card)
Vue.use(Pagination)
Vue.use(Scrollbar)
